"""empty message

Revision ID: b0d3dcbbee14
Revises: cc5aa5d7dbf1
Create Date: 2022-03-11 17:51:22.119133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d3dcbbee14'
down_revision = 'cc5aa5d7dbf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('order_id', table_name='orders')
    op.drop_constraint('orders_ibfk_1', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'customers', ['cust_id'], ['cust_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_ibfk_1', 'orders', 'customers', ['cust_id'], ['cust_id'])
    op.create_index('order_id', 'orders', ['cust_id'], unique=False)
    # ### end Alembic commands ###
